# Generated by Django 4.1.7 on 2023-03-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chistov_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('reviews', models.TextField(max_length=500, verbose_name='отзыв клиента')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания отзыва')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=200, verbose_name='Ваше сообщение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки сообщения'),
        ),
    ]
