# Generated by Django 4.1.7 on 2023-03-31 15:18

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Chistov_app', '0002_reviews_alter_contact_message_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50, verbose_name='Название фотосессии')),
                ('slag', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['time_create'], 'verbose_name': 'Входящие контакты', 'verbose_name_plural': 'Входящие контакты'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=200, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ваше имя:'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviews',
            field=models.TextField(max_length=500, verbose_name='Ваш отзыв'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, verbose_name='Видео')),
                ('time_create', models.DateField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chistov_app.category', verbose_name='Категории')),
            ],
        ),
    ]
