# Generated by Django 4.1.7 on 2023-04-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chistov_app', '0003_category_alter_contact_options_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name_category'], 'verbose_name': 'Категория фотосессии', 'verbose_name_plural': 'Категории фотосессии'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-time_create'], 'verbose_name': 'Входящий контакт', 'verbose_name_plural': 'Входящие контакты'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('-time_create',), 'verbose_name': 'Фото, видео', 'verbose_name_plural': 'Фото, видео'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ('-time_create',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='slag',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='media',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chistov_app.category', verbose_name='Категории фотосессии'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя клиента:'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviews',
            field=models.TextField(max_length=500, verbose_name='Отзыв клиента'),
        ),
    ]
